// Shared demo/seed data used by both the main planner (src/app/page.tsx) and
// the Spatial Design Engine (src/app/spatial/page.tsx). Extracted so the two
// pages don't maintain separate fake catalogues — mirrors supabase/seed_funding_au.sql
// per the original comment in page.tsx; Supabase isn't wired yet.
import type { FundingSource } from '@/lib/funding/match.ts';
import type { Product } from '@/lib/planner/plan.ts';

export const CATALOGUE: Product[] = [
  { id: 'p1', name: 'Sensory Swing (ceiling mount)', category: 'movement', sensory_tags: ['movement:seeks'], price: 420, funding_eligible: true, available_countries: ['*'], footprint_m: { w: 1.5, l: 1.5 } },
  { id: 'p2', name: 'Crash Mat', category: 'movement', sensory_tags: ['movement:seeks', 'pressure:seeks'], price: 260, funding_eligible: true, available_countries: ['*'], footprint_m: { w: 1.2, l: 1.8 } },
  { id: 'p3', name: 'Acoustic Wall Panels (set of 6)', category: 'acoustic', sensory_tags: ['noise:avoids'], price: 340, funding_eligible: true, available_countries: ['*'] },
  { id: 'p4', name: 'Noise-reducing Ear Defenders (5 pack)', category: 'acoustic', sensory_tags: ['noise:avoids'], price: 95, funding_eligible: true, available_countries: ['*'] },
  { id: 'p5', name: 'Bubble Tube with Dimmer', category: 'visual', sensory_tags: ['light:seeks'], price: 380, funding_eligible: true, available_countries: ['*'], footprint_m: { w: 0.5, l: 0.5 } },
  { id: 'p6', name: 'Blackout Blind Kit', category: 'visual', sensory_tags: ['light:avoids'], price: 150, funding_eligible: true, available_countries: ['*'] },
  { id: 'p7', name: 'Textured Tactile Wall Panels', category: 'tactile', sensory_tags: ['touch:seeks'], price: 220, funding_eligible: true, available_countries: ['*'] },
  { id: 'p8', name: 'Weighted Lap Pads (3 pack)', category: 'tactile', sensory_tags: ['pressure:seeks', 'touch:seeks'], price: 130, funding_eligible: true, available_countries: ['*'] },
  { id: 'p9', name: 'Soft Seating Pod', category: 'furniture', sensory_tags: ['pressure:seeks', 'noise:avoids'], price: 490, funding_eligible: false, available_countries: ['*'], footprint_m: { w: 1.0, l: 1.0 } },
  { id: 'p10', name: 'Wobble Cushions (4 pack)', category: 'movement', sensory_tags: ['movement:seeks'], price: 110, funding_eligible: true, available_countries: ['*'] },
];

// Mirrors supabase/seed_funding_au.sql — DRAFT data, pending review.
export const FUNDING: FundingSource[] = [
  { id: 'f1', name: 'NCCD Student with Disability Loading (Australian Government)', type: 'recurring', country: 'Australia', state_or_province: null, amount_range_min: null, amount_range_max: null, eligibility_rules_json: { nccd_tiers: ['supplementary', 'substantial', 'extensive'], notes: 'Recurrent federal loading; paid as a lump sum to school authorities — no fixed per-student amount.' }, deadline_date: null, source_url: 'https://www.education.gov.au/recurrent-funding-schools/schooling-resource-standard', last_verified_at: '2026-07-15' },
  { id: 'f2', name: 'Julia Farr Disability Inclusion Grants (SA, DHS)', type: 'one_off', country: 'Australia', state_or_province: 'SA', amount_range_min: 20000, amount_range_max: 100000, eligibility_rules_json: { notes: 'Schools may need an auspicing organisation — check current round guidelines.' }, deadline_date: null, source_url: 'https://dhs.sa.gov.au/how-we-help/grants/available-grants/julia-farr-disability-inclusion-grant-round-2-2025-2026', last_verified_at: '2026-06-20' },
  { id: 'f3', name: 'State Trustees Australia Foundation Community Inclusion Grants (VIC)', type: 'one_off', country: 'Australia', state_or_province: 'VIC', amount_range_min: null, amount_range_max: 20000, eligibility_rules_json: { notes: 'Requires ACNC-registered charity status — schools may apply via an associated charitable entity.' }, deadline_date: null, source_url: 'https://www.statetrustees.com.au/philanthropy-and-charitable-giving/granting/community-inclusion/', last_verified_at: '2026-07-28' },
  { id: 'f4', name: 'ACT Disability Inclusion Grants', type: 'one_off', country: 'Australia', state_or_province: 'ACT', amount_range_min: null, amount_range_max: 20000, eligibility_rules_json: { sectors: ['independent', 'catholic'], notes: 'Government entities ineligible; non-government incorporated entities may apply.' }, deadline_date: null, source_url: 'https://www.act.gov.au/money-and-tax/grants-funding-and-incentives/funding-to-improve-the-inclusion-and-participation-of-people-with-disability', last_verified_at: '2026-07-01' },
  { id: 'f5', name: 'BHP Western Australia Community Grants', type: 'corporate', country: 'Australia', state_or_province: 'WA', amount_range_min: null, amount_range_max: null, eligibility_rules_json: { notes: 'Grassroots grants in BHP WA operating regions; amounts vary per project.' }, deadline_date: null, source_url: 'https://www.bhp.com/about/our-businesses/western-australia-community-grants', last_verified_at: '2026-05-10' },
  // Non-education rows added per docs/MARKET-SCOPE.md (adopted 2026-08-08) — competitive
  // grants broadly applicable outside schools, "REVIEW:" flags real eligibility uncertainty.
  { id: 'f6', name: 'Regional Airports Program (Round 5)', type: 'one_off', country: 'Australia', state_or_province: null, amount_range_min: 20000, amount_range_max: 5000000, eligibility_rules_json: { sectors: ['airport'], notes: 'Owners/operators of regional airports or aerodromes; covers safety and accessibility upgrades up to 50% of project cost. REVIEW: Round 5 is closed as of this write — check business.gov.au for the next round before quoting to a user.' }, deadline_date: null, source_url: 'https://business.gov.au/grants-and-programs/regional-airports-program-round-5', last_verified_at: '2026-08-11' },
  { id: 'f7', name: 'Accessible Australia (NSW, Tranche 2)', type: 'one_off', country: 'Australia', state_or_province: 'NSW', amount_range_min: 20000, amount_range_max: 300000, eligibility_rules_json: { sectors: ['council', 'government', 'nfp'], notes: 'Government-owned and not-for-profit organisations only (commercial ineligible); facility must be in a public space. Funds Changing Places toilets, inclusive play spaces, and accessible beach/park equipment; caps vary by category ($20k-$300k). REVIEW: Tranche 2 closed 4 March 2026 — NSW-specific, not the "no restriction on who can apply" framing in docs/MARKET-SCOPE.md; correct that doc if reused. Check nsw.gov.au for the next tranche.' }, deadline_date: '2026-03-04', source_url: 'https://www.nsw.gov.au/grants-and-funding/accessible-australia-tranche-2', last_verified_at: '2026-08-11' },
  { id: 'f8', name: 'Higher Education Disability Support Program (Australian Government)', type: 'recurring', country: 'Australia', state_or_province: null, amount_range_min: null, amount_range_max: null, eligibility_rules_json: { sectors: ['university'], notes: 'Ongoing Commonwealth funding to Table A public universities: 55% enrolment-based, 45% reimbursement of individual student disability-support/equipment costs above $5,000/year. No fixed per-institution amount — paid to the institution, not applied for per-project. REVIEW: confirm a given university passes this through to sensory-space equipment purchases before quoting an amount.' }, deadline_date: null, source_url: 'https://www.education.gov.au/higher-education-disability-support-program', last_verified_at: '2026-08-11' },
];
